services:
  neo4j:
    image: neo4j:2025.02.0
    container_name: nfl-neo4j
    volumes:
      - ./data:/data
    environment:
      NEO4J_AUTH: "neo4j/782mbTLvP_HZ_ig"
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
      NEO4J_dbms_memory_heap_initial__size: "512m"
      NEO4J_dbms_memory_heap_max__size: "2G"
      NEO4J_dbms_connector_http_listen__address: "0.0.0.0:7474"
      NEO4J_dbms_connector_bolt_listen__address: "0.0.0.0:7687"
    ports:
      - "7474:7474"
      - "7687:7687"